language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*

matrix:
  exclude:
    - php: 5.6
      env: SYMFONY_VERSION=4.0.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --dev --no-interaction

script:
   - phpunit --testsuite=Unit
